interpretml/interpret-community

python/interpret_community/common/constants.py
python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/mimic/models/lightgbm_model.py
python/interpret_community/mimic/models/tree_model.py
python/interpret_community/mimic/models/tree_model_utils.py
python/interpret_community/shap/tree_explainer.py
requirements.txt

- pin tf and lightgbm versions to fix the failing build after new versions released
- fix some doc that was referencing azure
- remove unused constants

pin tf and lightgbm versions, fix some doc, remove unused constants

---

python/interpret_community/common/constants.py
python/interpret_community/mimic/models/lightgbm_model.py
requirements.txt

fix lightgbm serialization in v2.3.0
the lightgbm update broke the custom serialization logic we have for automl and our tests
the model string is now a top-level param

fix lightgbm serialization in v2.3.0

---

python/interpret_community/__init__.py

add infrastructure to create a logging file on import if an env variable is specified
If the 'INTERPRETC_LOGS' environment value is specified, we log any logging.info statements to the specified location on disk

add infrastructure to create a logging file on import if an env variable is specified

---

python/interpret_community/common/constants.py
python/interpret_community/dataset/dataset_wrapper.py
python/interpret_community/mimic/mimic_explainer.py
test/test_mimic_explainer.py
test/test_timestamp_featurizer.py

fix indexes with pandas
- add pandas indexes support, specifically for explaining timeseries models
- add datetime featurization
- fix bug in string indexing with one-hot-encoding for models that can't handle categoricals natively

fix indexes with pandas

---

python/interpret_community/explanation/explanation.py

only get the eval_y_predicted and eval_data from explanation in _local_data method used by data contract if _DatasetsMixin exists on the explanation
required for explanation dashboard widget to work on downloaded explanations without data

fix data on explanation

---

python/interpret_community/mimic/models/lightgbm_model.py

For environments where lightgbm is not installed, users can see multiple stacked warnings when importing from interpret-community package:
```
Could not import lightgbm, required if using LGBMExplainableModel
```
This PR gets rid of wacky import warning for lightgbm appearing multiple times.

get rid of wacky import warning for lightgbm appearing multiple times

---

python/interpret_community/explanation/explanation.py

Fixes a bug that was showing up in azureml-interpret. Download only produces per_class_rank, so we need to use that.

switch to use rank from downloads for num_classes

---

python/setup.py

update shap dependency to 0.33.0
also some minor cleanup in setup.py:
- removed unused logic for major/patch version
- add python 3.7 classifier
- reference github url which should give interpret-community a github statistics panel on the pypi webpage

update shap dependency to 0.33.0

---

visualization/mlchartlib/package.json
visualization/mlchartlib/src/AccessibleChart.scss
visualization/mlchartlib/src/AccessibleChart.tsx

Currently graph is not accessible by keyboard, and when using Narrator, it says "image" when going over the GridChart and does not pronounce date from the table.
This change is making it accessible by keyboard and when using Narrator, it pronounces values from the table (and skips GridChart)

Made changes to AccessibleChart so that it is accessible by keyboard and Narrator

---

visualization/mlchartlib/package.json
visualization/mlchartlib/src/AccessibleChart.tsx

Accessibility tests on our side are failing because having tabindex="0" and aria-hidden="true" is confusing. Tabindex allows item to be focusable by keyboard, but aria-hidden is hiding it from the Narrator.
Since we are currently not able to do anything on the chart after focusing with a keyboard (like going into each data point), we can just remove it.

Removed tabindex from GridChart

---

python/interpret_community/common/constants.py
python/interpret_community/dataset/dataset_wrapper.py
python/interpret_community/mimic/mimic_explainer.py
test/models.py
test/test_mimic_explainer.py

Support timeseries models.  Add reset_teacher option for mimic explainer to allow index to be reset on teacher model but ignored on surrogate model.  Also fixed datetime check in our featurizer for surrogate models.

support timeseries models

---

python/docs/conf.py
python/interpret_community/common/blackbox_explainer.py
python/interpret_community/common/constants.py
python/interpret_community/common/explanation_utils.py
python/interpret_community/common/metrics.py
python/interpret_community/common/model_wrapper.py
python/interpret_community/common/policy.py
python/interpret_community/common/progress.py
python/interpret_community/community/__init__.py
python/interpret_community/explanation/explanation.py
python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/permutation/metric_constants.py
python/interpret_community/permutation/permutation_importance.py
python/interpret_community/shap/__init__.py
python/interpret_community/shap/deep_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/kwargs_utils.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py
python/interpret_community/tabular_explainer.py
python/interpret_community/widget/explanation_dashboard.py
python/interpret_community/widget/explanation_dashboard_input.py
python/scripts/build-docs.ps1
test/test_explain_model.py

Changes just to docstrings, except to conf.py to get local builds to behave nicely in terms of linking.
In general:
1. changed "user" terminology to "you" to make it more personal
2. where "we" was used, either named actor or went with passive form of sentence 
3. checked for proper user of brand names.

Light doc pass.

---

visualization/mlchartlib/package.json
visualization/mlchartlib/src/AccessibleChart.scss

Currently table is taking space with a lot of empty space on the page if there is a lot of data. Changing display to block resolves this issue.

Changed plotly chart table to have display block

---

python/interpret_community/widget/explanation_dashboard.py

improved gevent error message to be:
Error: gevent package is missing, please run 'conda install gevent' or 'pip install gevent' or 'pip install interpret-community[visualization]'

improved gevent error message

---

python/interpret_community/explanation/explanation.py

fix aggregation logic to use mean
We were seeing issues where only one column appeared in the global importance values with AutoML.
After AutoML featurization, all except one of the columns are TFIDF columns (and I'm guessing others are dropped).  When computing the global feature importance values for sparse data, I'm currently using median, which means that columns with very sparse feature importances will just have an importance value of 0.  Using median preserves sparsity, but it also makes most of the global feature importances zero, which seems like it might not be as useful.  I will update it to use mean instead.  Even if I use mean, most of the values will be very close to zero anyway, so it's a bit questionable about how useful the global feature importances are.  For the raw …

fix aggregation logic to use mean

---

test/test_serialize_explanation.py

Import ABC from collections.abc instead of collections for Python 3 compatibility

---

python/interpret_community/mimic/mimic_explainer.py
test/test_mimic_explainer.py

fixed timeseries error where index column not removed for surrogate model when using reset_teacher on evaluation

fixed timeseries error where index column not removed for surrogate model when using reset_teacher on evaluation

---

python/setup.py

- updated interpret-core to 0.1.21
- import ABC from collections.abc instead of collections for Python 3 compatibility
- fixed timeseries error where index column not removed for surrogate model when using reset_teacher on evaluation

release v0.10.0

---

python/interpret_community/mimic/mimic_explainer.py
test/common_utils.py
test/raw_explain/test_raw_explanation.py
test/test_mimic_explainer.py

fix for local importance values in binary classification linear surrogate model on sparse data
the local importance values in binary classification case on sparse data need to be a list of [-, +] local importance values even though a regression model is used to compute the importance values

fix for local importance values in binary classification linear surrogate model on sparse data

---

python/interpret_community/permutation/permutation_importance.py
test/test_pfi_explainer.py

improve error message for PFI explainer on missing true_labels
The new error message should make it clearer to users that the true_labels parameter is required for PFI, unlike other explainers:

improve error message for PFI explainer on missing true_labels

---

python/interpret_community/permutation/permutation_importance.py
test/test_pfi_explainer.py

fixing PFI explainer error when passing true_labels on kwargs
follow-up to previous PR, the recently added check makes PFI fail when true_labels is passed on kwargs instead of args

fixing PFI explainer error when passing true_labels on kwargs

---

visualization/dashboard/package.json
visualization/dashboard/src/Localization/en.json
visualization/dashboard/src/MLIDashboard/Cohort.ts
visualization/dashboard/src/MLIDashboard/Controls/AxisConfigurationDialog/AxisConfigDialog.tsx
visualization/dashboard/src/MLIDashboard/Controls/DatasetExplorerTab/DatasetExplorerTab.styles.ts
visualization/dashboard/src/MLIDashboard/Controls/DatasetExplorerTab/DatasetExplorerTab.tsx
visualization/dashboard/src/MLIDashboard/Controls/DependencePlot/DependencePlot.styles.ts
visualization/dashboard/src/MLIDashboard/Controls/DependencePlot/DependencePlot.tsx
visualization/dashboard/src/MLIDashboard/Controls/FeatureImportanceBar/FeatureImportanceBar.tsx
visualization/dashboard/src/MLIDashboard/Controls/ModelPerformanceTab/ModelPerformanceTab.tsx
visualization/dashboard/src/MLIDashboard/Controls/MultiICEPlot/MultiICEPlot.tsx
visualization/dashboard/src/MLIDashboard/Controls/WhatIfTab/WhatIfTab.styles.ts
visualization/dashboard/src/MLIDashboard/Controls/WhatIfTab/WhatIfTab.tsx
visualization/dashboard/src/MLIDashboard/FabricStyles.ts
visualization/dashboard/src/MLIDashboard/JointDataset.ts

Add formatted tooltips to all charts (except box plots, which are not customizable in plotly at this time).
Set better defaults for charts.
Add 'count' option to data profile histogram view.
Fix bugs encountered while testing

Tooltips for charts and bugfixes

---

requirements.txt

fix keras dependency issue
Keras was recently updated which broke our builds.
Note: keras will be removed once we update to the next SHAP release, since it will be moved under tf.keras API

fix keras dependency issue

---

test/test_notebooks.py

set use_cdn=False in notebook tests

set use_cdn=False in notebook tests

---

python/interpret_community/common/blackbox_explainer.py
python/interpret_community/common/constants.py
python/interpret_community/common/model_wrapper.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py
python/interpret_community/widget/explanation_dashboard_input.py
test/datasets.py
test/test_mimic_explainer.py

Fix string class labels issue with mimic explainer
Specifically, for some classifiers like SGDClassifier that don't have a predict_proba method and don't output probabilities, we were failing on using string labels.  The best solution is in the model_wrapper, where we can wrap the model to our specifications to output probabilities as a boolean vector array where class i = 1 and all else are 0.  This fix ensures that any classification models without a predict_proba (we will need to whitelist them) can fit our specifications for blackbox explainers.
Resolves user issue:
https://github.com/MicrosoftDocs/azure-docs/issues/59129#event-3571829770

fix string class labels issue with mimic explainer

---

devops/templates/create-env-step-template.yml

Retrying a job in an ADO pipeline would often fail because the Artifacts are immutable. Have the 'environment information' artifact append the job attempt in order to work around this.

Fix for job retries in pipelines

---

test/test_mimic_explainer.py

fixed macos failing tests in nightly build pipeline
Nightly builds have been failing:
https://dev.azure.com/responsibleai/interpret-community/_build?definitionId=41
Specifically, the macos tests seem to be failing.  Reduced tolerance in the validation logic to make them pass.

fixed macos failing tests in nightly build pipeline

---

python/interpret_community/explanation/explanation.py
requirements.txt

fix break in interpret api reference for latest version
apparently, when we upgraded to latest interpret-core:
https://github.com/interpretml/interpret-community/pull/299
the tests were still running on the older version of interpret-core.  This PR fixes the breaking change in interpret-core.

fix break in interpret api reference for latest version

---

python/interpret_community/__init__.py

release interpret-community 0.14.3
- hotfix for breaking change in latest version of dependency interpret-core perf_dict api

release interpret-community v0.14.3

---

python/interpret_community/common/model_wrapper.py
test/common_utils.py
test/test_explain_model.py

Fix for customer where predict function was returning probabilities instead of predicted values for a classifier, and the model did not have a predict_proba method.  We can detect and handle this scenario in the model wrapper.  The crucial part is to return the argmax of the probabilities in the predict function for this scenario, since predict_proba is already handled by the wrapper - in order to ensure that the eval_y_predicted on the explanation are predictions and not probabilities.

handle case where classifier has predict function that returns probabilities in model wrapper

---

python/interpret_community/shap/tree_explainer.py
requirements.txt
test/common_tabular_tests.py
test/constants.py
test/test_mimic_explainer.py
test/test_misc_explainers.py

added tests for shap_values_output for tree explainer and mimic explainer, fixed issue with XGBoost and TreeExplainer case
Note latest XGBoost doesn't work with shap 0.34.0 so I pinned it, there is a serialization issues which is already fixed in latest shap, but requires us upgrading to it.

added shap_values_output tests and fixed issue

---

python/interpret_community/__init__.py

- fix open in new tab on public VMs (specifically tested on Azure DSVM)
-  handle case where classifier has predict function that returns probabilities in model wrapper
-  added tests for shap_values_output for tree explainer and mimic explainer, fixed issue with XGBoost and TreeExplainer case

release interpret-community v0.14.4

---

test/test_mimic_explainer.py

update tests to support lightgbm 3.0 update
lightgbm 3.0 was releases yesterday, causing some of our tests to start failing.
This PR updates some of those tests and disables two tests that require fixes in shap TreeExplainer to support sparse output.

update tests to support lightgbm 3.0 update

---

python/interpret_community/_internal/raw_explain/data_mapper.py
python/interpret_community/_internal/raw_explain/feature_mappers.py
test/raw_explain/test_data_mapper.py

Optimize data mapper memory usage by using sparse format (for raw features transformations)
In the test case added, there was a mapping from 8000 raw columns to 80000 engineered columns, which resulted in >4.7 GB dense matrix in memory (which led to OOM on my machine).  Using sparse format resolved this issue and vastly reduced overall memory usage.

optimize data mapper memory usage

---

python/interpret_community/__init__.py
python/interpret_community/version.py
python/setup.py

for reference, please see stack overflow:
https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package
note it is not recommended to do what we recently switched to, which is importing the package in setup.py, because it causes a lot of issues during install, forcing the user to install all of the dependencies before running pip install on the interpret-community setup.py.

fix issues with importing version in setup.py before dependencies installed

---

notebooks/advanced-feature-transformations-explain-local.ipynb
notebooks/explain-binary-classification-local.ipynb
notebooks/explain-multiclass-classification-local.ipynb
notebooks/explain-regression-local.ipynb
notebooks/simple-feature-transformations-explain-local.ipynb
test/test_notebooks.py

Add true_y parameter to ExplanationDashboard notebooks to demonstrate additional functionality
This allows users to see:
1.) The model performance statistics
2.) Have additional true_y data available in dropdowns for various graphs

add true_y parameter to ExplanationDashboard notebooks to demonstrate additional functionality

---

python/interpret_community/lime/__init__.py
python/interpret_community/lime/lime_explainer.py
python/setup.py
requirements.txt
test/test_lime_explainer.py
test/test_through_ext.py

move LIME wrapper from azureml-contrib-interpret package to interpret-community
This is so we can deprecate and remove the azureml-contrib-interpret package to reduce the number of packages and engineering overhead.

move LIME from azureml-contrib-interpret package to interpret-community

---

python/interpret_community/common/explanation_utils.py
test/test_mimic_explainer.py

fix tolist error for sparse feature importances and sparse raw_to_output_map on creating raw explanation
This error seems to occur when the engineered feature importances are sparse and the raw_to_output_map is sparse for regression scenario.
The error is related to this recent data mapper memory optimization:
https://github.com/interpretml/interpret-community/pull/313

fix tolist error for sparse feature importances and sparse raw_to_output_map on creating raw explanation

---

python/interpret_community/version.py

-  fix tolist error for sparse feature importances and sparse raw_to_output_map on creating raw explanation
-  move LIME from azureml-contrib-interpret package to interpret-community
-  fix error during visualization on explanation with id for eval_y_predicted and eval_y_predicted_proba in datasets mixin
-  add true_y parameter to ExplanationDashboard notebooks to demonstrate additional functionality

release interpret-community v0.15.1

---

python/interpret_community/widget/js/main.js

When using a credentialed VM with axios library for requests, even though responses were being sent back with data for some reason the dashboard was not getting updated, which I traced to a bug in how the axios library was used - we need to use response.data to get the axios data, and then we need to call .data again to get the actual data in the json response object.  With this bug what if analysis and ICE should be fixed - currently they seem to be showing but actually when doing what if or ICE plots they never update.

fix credentialed VM response data when using axios library

---

python/interpret_community/widget/explanation_dashboard.py
python/interpret_community/widget/templates/inlineDashboard.html
test/test_notebooks.py

removes the use_cdn flag and related code from explanation dashboard in order to simplify maintenance.  Users who continue to pass use_cdn flag will see a warning that it has been deprecated.

remove cdn from explanation dashboard

---

python/interpret_community/mimic/models/lightgbm_model.py
test/test_serialize_explainer.py

fix issue with serializing the lightgbm surrogate model on mimic explainer for lightgbm >= 3.0.0

fix issue with serializing the lightgbm surrogate model on mimic explainer for lightgbm >= 3.0.0

---

python/interpret_community/version.py

- fix issue with serializing the lightgbm surrogate model on mimic explainer for lightgbm >= 3.0.0

release interpret-community 0.15.3

---

python/interpret_community/dataset/dataset_wrapper.py
python/interpret_community/dataset/decorator.py
python/interpret_community/explanation/explanation.py
python/interpret_community/mimic/mimic_explainer.py
test/common_utils.py
test/test_mimic_explainer.py

various memory optimizations in interpret-community done as part of integration with another product
- where possible use _local_importance_values since local_importance_values converts from numpy to list
- avoid typed_dataset in some paths since that creates a new pandas dataframe
- add clear_references parameter to DatasetWrapper such that it can be cleared after use, which should reduce memory usage - note this is only for users who know what they are doing
- added test for dense and wide data which can be used for future performance testing as well

various memory optimizations

---

python/interpret_community/dataset/dataset_wrapper.py
python/interpret_community/mimic/mimic_explainer.py

When updating to scikit-learn 0.24, one hot encoder can no longer handle apply on columns of object type.  This caused the test case test_explain_model_categorical to start failing for mimic explainer:
```
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
For this specific case, where the dataset has categorical values, we explicitly cast the dataset to float prior to fitting the one-hot-encoder which resolves the issue.

fix categorical handling for scikit-learn 0.24 during one hot encoding for failing test

---

python/interpret_community/_internal/raw_explain/feature_mappers.py
python/interpret_community/common/constants.py
python/interpret_community/common/explanation_utils.py
python/interpret_community/mimic/mimic_explainer.py
test/test_explanation_utils.py

various memory optimizations to the explanation-related APIs, particularly explain_global, including:
1.) preventing matrix multiply if matrix is identity in engineered to raw mapping (which happens very often) - this significantly reduces memory usage
2.) differentiating between call from explain_global vs explain_local when entering _explain_local which allows us to skip some duplicate computations which lead to higher memory usage
3.) refactoring out into functions (eg _explain_local_helper) which allows GC of various temporary variables (I could have also used del but it looks much uglier)
These memory optimizations allowed AzureML designer run to complete on 6k X 40k dense dataset (with passed transformations)

various memory optimizations for explain API

---

python/interpret_community/common/exception.py
python/interpret_community/mimic/mimic_explainer.py
test/test_mimic_explainer.py

- Accuracy/r2_score for predictions from teacher model and surrogate model

Add replication metric computation in MimicExplainer

---

python/interpret_community/version.py

- Add _serialize_json_safe to utils and add unit tests
- various memory optimizations in interpret-community done as part of integration with another product
1.) where possible use _local_importance_values since local_importance_values converts from numpy to list
2.) avoid typed_dataset in some paths since that creates a new pandas dataframe
3.) add clear_references parameter to DatasetWrapper such that it can be cleared after use, which should reduce memory usage - note this is only for users who know what they are doing
4.) added test for dense and wide data which can be used for future performance testing as well
- Pickling and Unpickling MimicExplainer and Surrogate models
- fix categorical handling for scikit-learn 0.24 during one hot encoding for failing test
- Add unit test for …

release interpret-community v0.16.0

---

requirements.txt

pypi upload scripts are failing due to old version of setuptools, see issue and suggested fix for context:
https://github.com/actions/setup-python/issues/165

upgrade setuptools to latest to fix pypi upload error

---

python/interpret_community/common/constants.py
python/interpret_community/explanation/explanation.py
test/common_tabular_tests.py
test/common_utils.py
test/test_explain_model.py
test/test_serialize_explanation.py

A user wanted to save and load explanations using save/load methods to json (without using explanationclient), however these were not deserializing the local importance values properly as a numpy array, leading to exceptions when viewed in widget.    This PR resolves this.  In the process of adding tests, I found a host of other issues:
1.) We weren't saving/loading some properties like eval_data, init_data and pred_y/pred_proba_y (fixed in this PR)
2.) The save/load explanation code can't handle sparse data, I've added a disabled test and created a github issue to track this (https://github.com/interpretml/interpret-community/issues/378)

fix load explanation methods for numpy based variables

---

python/interpret_community/common/explanation_utils.py

Removes the following private methods as these are not being called from anywhere in the interpret-community SDK:-
- _transform_data
- _unsort_2d
Fixes https://github.com/interpretml/interpret-community/issues/372

Remove unused private methods

---

python/interpret_community/version.py

patch release 0.17.1 of interpret-community SDK
- fix sphinx documentation issue with constants params
- remove private methods as these are not being called from anywhere in the interpret-community SDK:
- _transform_data
- _unsort_2d

release interpret-community 0.17.1

---

python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/mimic/models/explainable_model.py
python/interpret_community/mimic/models/lightgbm_model.py
python/interpret_community/mimic/models/linear_model.py
python/interpret_community/mimic/models/tree_model.py
test/common_tabular_tests.py
test/test_lime_explainer.py
test/test_mimic_explainer.py

related to issue:
https://github.com/interpretml/interpret-community/issues/390
the static "explainable_model_type" method was not 1.) called correctly from mimic explainer 2.) defined correctly on surrogate models
I fixed both issues and added more validation logic.  This doesn't actually throw an error, but for tree surrogate models we were one-hot-encoding instead of only string indexing

fix model type parameter being called and defined incorrectly in mimic explainer

---

python/README.md
python/interpret_community/version.py

- Adds missing 'intercept' field on local explanation 'mli' data.  Resolves issues: microsoft/responsible-ai-widgets#367 #260
- Fix sphinx doc warnings
- Update readme with latest package description
- Fix model type parameter being called and defined incorrectly in mimic explainer.  Resolves issue: #390
- Removed LIME warning, made it an exception inside the explainer if package is missing

release interpret-community 0.17.2

---

python/interpret_community/_internal/raw_explain/feature_mappers.py
python/interpret_community/common/base_explainer.py
python/interpret_community/explanation/explanation.py
python/interpret_community/mimic/models/explainable_model.py
test/test_misc_explainers.py

since we don't support python 2.7 anymore, and haven't for a while, it makes sense to use the newer ABC abstract classes instead of ABCMeta
also fixes retry logic in one of the tests

update abstract classes to use ABC instead of ABCMeta

---

python/interpret_community/mimic/mimic_explainer.py

remove annoying warning in notebook relating to categorical features being specified when the list is empty in mimic explainer for a lightgbm surrogate model:

remove warning on mimic explainer relating to categorical features

---

python/interpret_community/version.py

- upgrade shap to 0.39.0, which deprecated python 3.5 and added python 3.8 support
- Add cuML GPU SHAP KernelExplainer 
- update abstract classes to use ABC instead of ABCMeta
- remove warning on mimic explainer relating to categorical features
- Add test case of serializing pandas timestamp
- add sparse feature importance support for lightgbm surrogate model
- add support for drop parameter in one hot encoder

release interpret-community 0.18.0

---

python/interpret_community/common/gpu_kmeans.py

On any import seeing warning, removing the warning in gpu_kmeans.py since it appears even if user is not trying to use it:
```
>>> from interpret_community import TabularExplainer
c:\interpret-community\python\interpret_community\common\gpu_kmeans.py:32: UserWarning: cuML is required to use GPU explainers. Check https://rapids.ai/start.html         for more information on how to install it.
for more information on how to install it.")
cuML is required to use GPU explainers. Check https://rapids.ai/start.html         for more information on how to install it.
```

fix gpu_kmeans warning on any import

---

python/interpret_community/common/explanation_utils.py
python/interpret_community/explanation/explanation.py
python/interpret_community/shap/gpu_kernel_explainer.py
test/test_explanation_utils.py
test/test_mimic_explainer.py

for explanation methods:
get_ranked_local_values
get_ranked_local_names
get_local_importance_rank
implement missing sparse logic.  Also, compress local importance values to dense format based on whether it will be more optimal storage when converting an engineered explanation to a raw explanation.
Fix scores representation to be dense when passing to widget (otherwise ExplanationDashboard fails).
Also, removes another spurious cuML warning message on library import.

implement sparse scenario for getting ranked values and indexes on local explanation

---

python/interpret_community/version.py

- includes fix to implement sparse case for methods:
- get_ranked_local_values
- get_ranked_local_names
- get_local_importance_rank
and compress local importance values to dense format based on whether it will be more optimal storage when converting an engineered explanation to a raw explanation
- remove another spurious cuML warning message on library import.

release interpret-community 0.18.1

---

python/interpret_community/explanation/explanation.py
test/common_utils.py
test/raw_explain/test_raw_explanation.py

It seems y_pred and y_pred_proba are not added from the engineered explanations to raw explanations. This causes the model performance tab to not show y_pred/y_pred_proba for raw explanations.

Add predicted and predicted probabilities to raw explanations

---

notebooks/explain-binary-classification-local-gpu.ipynb
python/interpret_community/shap/gpu_kernel_explainer.py

PR changes the version check to accommodate all versions above 0.18, and fixes a typo in the notebook example

Update cuML version for GPUKernelExplainer

---

devops/templates/create-env-step-template.yml
devops/templates/test-run-step-template.yml

Move visualization requirements to end of environment install.
The problem I was hitting was that the viz requirements would install the released version of interpret-community with older dependencies, so new dependencies would not get tested.  The viz requirements includes raiwidgets which depends on responsibleai package which depends on an older version of interpret-community.

move viz requirements to end of environment install

---

README.md
python/interpret_community/common/blackbox_explainer.py
python/interpret_community/common/explanation_utils.py
python/interpret_community/common/model_wrapper.py
python/interpret_community/common/structured_model_explainer.py
python/interpret_community/dataset/dataset_wrapper.py
python/interpret_community/explanation/explanation.py
python/interpret_community/lime/lime_explainer.py
python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/mimic/models/linear_model.py
python/interpret_community/shap/deep_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/tabular_explainer.py
test/test_serialize_explanation.py

remove shap DenseData from supported input data
resolves issue: https://github.com/interpretml/interpret-community/issues/401
technically this is a breaking change, however shap github repo itself made this class private, so we are only following the precedent for this by removing support for it here

remove shap DenseData from supported input data

---

python/interpret_community/mimic/model_distill.py

Seems like the older way of computing gives the following error:-
"
RuntimeWarning: divide by zero encountered in true_divide
new_values = np.log(values / (1 - values))
"
Changing to logit() from scipy fixes this.

Use scipy logit() function

---

python/interpret_community/version.py

- fix error when creating a raw explanation from an engineered explanation that does not have a DatasetsMixin

release interpret-community 0.19.1

---

python/interpret_community/explanation/explanation.py
test/common_utils.py
test/test_explanation_dashboard.py

fixes issue:
https://github.com/interpretml/interpret-community/issues/429
the fix is to handle boolean labels in the _perf_dict method which is called when the dashboard gets the explanation data as a dictionary for visualization.  Previously, we would try to subtract the boolean values which would lead to an error:
```
TypeError: numpy boolean subtract, the - operator, is not supported, use the bitwise_xor, the ^ operator, or the logical_xor function instead.`
```
Instead, we should be checking for equality via == instead.
The PR includes both the fix for the issue and a test that was used to reproduce the problem.

fix explanation dashboard failing to run on dataset with boolean target labels

---

README.md

the table containing the explainers with header "Interpretability Technique|Description|Type" in the readme is not displaying properly, this PR will fix it

[doc] Fix table in readme

---

python/interpret_community/explanation/explanation.py
python/interpret_community/mimic/mimic_explainer.py
test/common_tabular_tests.py
test/raw_explain/test_raw_explanation.py
test/transformation_utils.py

When computing a raw explanation by passing in the transformations object to mimic explainer, instead of computing the explanation and then using a feature map, if include_local=False and no local importance values are computed the resulting explanation computation will error out.  This is because the code will try to transform the explanation to raw from engineered, but when aggregating the local importance values have already been computed as raw and mapped in the explain_local method.  The most correct way to handle this is to prevent the second transformation from being done, since the aggregated explanation is already in terms of raw importances and the transformation is not needed.

fix raw aggregated explanation failing to compute when transformations passed to mimic explainer and include_local=False

---

python/interpret_community/version.py

- Removed old ExplanationDashboard.  The old namespace still exists but widget won't display anything and will print a warning now.  Please use the ExplanationDashboard from the raiwidgets package instead.
Please install raiwidgets from pypi by running:
```pip install --upgrade raiwidgets```
The dashboard can be run with the same parameters in the new namespace:
```from raiwidgets import ExplanationDashboard```
For more information on the new widget please see: https://github.com/microsoft/responsible-ai-widgets
- Fixed raw aggregated explanation failing to compute when transformations passed to mimic explainer and include_local=False

release interpret-community 0.20.0

---

python/interpret_community/explanation/explanation.py
python/interpret_community/widget/explanation_dashboard.py
requirements-vis.txt
test/test_explanation_dashboard.py

- add tests to increase code coverage.  I also found an issue with the latest interpret dashboard (due to breaking schema changes) while adding the test which is fixed in this PR.

add test for old explanation dashboard and interpret dashboard

---

python/interpret_community/tabular_explainer.py
test/test_explain_model.py

- Based on experience of debugging with customer, when TabularExplainer fails with default use_gpu=False on GPUKernelExplainer it prints the last warning, even though it will always fail.  This PR separates it out so it only runs when use_gpu flag is on.  The previous logic would skip every explainer if use_gpu=True other than GPUKernelExplainer, but still for some reason run it even if use_gpu=False.  By separating it out, the customer will once again see the most useful error message from the last default catch-all KernelExplainer.

change explainers tabular explainer runs based on use_gpu flag

---

python/setup.py
requirements.txt

- bump shap version upper bound to 0.40.0
- bump interpret-core version upper bound to 0.2.7

version bump for shap 0.40.0 and interpret-core 0.2.7

---

python/interpret_community/version.py

- version bump for shap 0.40.0 and interpret-core 0.2.7
- removed the pin on lightgbm package due to recent build break with new lightgbm release 3.3.1 and fixed the serialization logic to handle the new lightgbm model version
- upgraded tensorflow and xgboost test dependencies
- added support for keras scikit classifier and regressor to model wrapper
- fixed nightly build breaking due to new scikit-learn package which breaks model function serialization

release interpret-community 0.22.0

---

.readthedocs.yaml

fixes warnings about pandas and other libraries in the docs build, which was causing some documentation to not be built

add more dependencies to docs build to fix warnings

---

python/setup.py

Removing the pin for numba<0.54.0.  This pin does not belong in interpret-community package.  Downstream users will need to make sure that if they are using latest numpy, they use numba>=0.54.0, and for some older versions of numpy (not sure what the exact threshold is) they will need to pin numba<0.54.0.

remove numba dependency pin

---

python/interpret_community/explanation/explanation.py
test/test_serialize_explanation.py

The problem ocurrs in the scenario when saved explanations are loaded from disk and saved again. This leads to inconsistent types for init_data where the init_data type is changed from numpy arrays to list. This causes the following problem on a save_explanations()
def save_explanation(explanation, path, exist_ok=False):
"""Serialize the explanation.
:param explanation: The Explanation to be serialized.
:type explanation: Explanation
:param path: The path to the directory in which the explanation will be saved. By default, must be a new directory
to avoid overwriting any previous explanations. Set exist_ok to True to overrule this behavior.
:type path: str
:param exist_ok: If False (default), the path provided by the user must not already exist and will be created by
this function. If …

Fix multiple save()/load() bug

---

python/interpret_community/version.py

- fix sphinx doc build failures in interpret-community
- sort imports using isort
- add more dependencies to docs build to fix warnings
- remove numba dependency pin
- add more flake8 extensions
- fix multiple save()/load() bug
- add flake8-breakpoint to avoid code checkin with active breakpoints

release interpret-community v0.23.0

---

python/interpret_community/common/explanation_utils.py
python/interpret_community/common/warnings_suppressor.py
python/interpret_community/mimic/models/lightgbm_model.py
python/interpret_community/mimic/models/linear_model.py
python/interpret_community/mimic/models/tree_model.py
python/interpret_community/shap/deep_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py

Customer was seeing warnings printed:
```
2022-01-03 19:51:39.840150: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/mic/lib::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64/
2022-01-03 19:51:39.840205: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```
We never actually import tensorflow directly, but shap does.  This PR suppresses the tensorflow warning on shap import.

suppress tensorflow warnings that may sometimes occur on import

---

python/interpret_community/__init__.py
python/interpret_community/explanation/__init__.py
python/interpret_community/explanation/explanation.py
python/interpret_community/explanation/serialization.py
python/interpret_community/mlflow/mlflow.py
tests/test_serialize_explanation.py

add support for serializing explanations using save_explanation and load_explanation with sparse data
fixes issue:
https://github.com/interpretml/interpret-community/issues/378
bug description:
```
Describe the bug
Save_explanation and load_explanation methods can't handle sparse local importance values.
We need to add the logic, similar to that in explanation client, to handle sparse data.
See disabled test "test_save_and_load_sparse_explanation"
```

add support for serializing explanations using save_explanation and load_explanation with sparse data

---

devops/templates/test-run-step-template.yml
python/interpret_community/mimic/models/lightgbm_model.py
python/interpret_community/shap/deep_explainer.py

Seeing flake8 errors on builds, even though the builds succeed:
This PR tries to fix it by moving the flake8 check before the publish tests step, and it also removes the code to install flake8 et al because these should already be installed from the test dependencies file (https://github.com/interpretml/interpret-community/blob/master/requirements-test.txt).
The PR sets "failOnStderr: true" to fail the linting task run on bash if there is stderr.
Also, it splits the linting and isort into two tasks, otherwise the build succeeds even if linting fails currently, since bash task only checks the output of the last run statement.

fix flake8 error on builds

---

python/interpret_community/common/model_wrapper/__init__.py
python/setup.py

a downstream package has issues because it reimported these from interpret-community, which did not reimport them from ml-wrappers

fix reimports from ml-wrappers package for WrappedClassificationModel, WrappedRegressionModel

---

devops/PR-Gate.yml

- remove the devops unit tests from PR gate since we are now using github actions for those

remove devops unit tests from PR gate

---

python/interpret_community/mimic/mimic_explainer.py
tests/test_mimic_explainer.py

Make function _get_surrogate_model_replication_measure() public

---

tests/test_serialize_explanation.py

The nightly build is failing for macos platform due to tolerance checks in serialization backcompat test.
This PR decreases the tolerance in the check to fix the macos tests.

decrease tolerance on serialization check for macos test builds

---

README.md
python/interpret_community/_internal/raw_explain/data_mapper.py
python/interpret_community/_internal/raw_explain/data_mapper_utils.py
python/interpret_community/_internal/raw_explain/feature_mappers.py
python/interpret_community/_internal/raw_explain/raw_explain_utils.py
python/interpret_community/adapter/explanation_adapter.py
python/interpret_community/common/aggregate.py
python/interpret_community/common/blackbox_explainer.py
python/interpret_community/common/explanation_utils.py
python/interpret_community/common/gpu_kmeans.py
python/interpret_community/common/structured_model_explainer.py
python/interpret_community/explanation/explanation.py
python/interpret_community/lime/lime_explainer.py
python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/mimic/models/lightgbm_model.py
python/interpret_community/mimic/models/linear_model.py
python/interpret_community/mimic/models/tree_model.py
python/interpret_community/mimic/models/tree_model_utils.py
python/interpret_community/permutation/permutation_importance.py
python/interpret_community/shap/deep_explainer.py
python/interpret_community/shap/gpu_kernel_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py
python/interpret_community/tabular_explainer.py
python/interpret_community/widget/explanation_dashboard.py

We should be using numpy.ndarray in python docs because that is the type of the numpy arrays instead of numpy.array which is the function used to create the arrays.
This PR updates the docs.

replace numpy.array with numpy.ndarray in docs

---

requirements-test.txt

It seems like the notebook tests are failing with the following exception:-
File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
exec(co, module.__dict__)
File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/dash/__init__.py", line 5, in <module>
from .dash import Dash, no_update  # noqa: F401,E402
File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
exec(co, module.__dict__)
File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/dash/dash.py", line 16, in <module>
import flask
File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
from jinja2 import Markup, escape
File …

Update requirements-test.txt to pin markupsafe<2.1.0

---

notebooks/explain-regression-mimic-explainer.ipynb
tests/test_notebooks.py

Adding a new notebook showing the replication measure for global surrogate model. This is with reference to the github issue https://github.com/interpretml/interpret-community/issues/452. 

Add notebook replication measure of global surrogate model

---

devops/templates/all-tests-job-template.yml
devops/templates/create-env-step-template.yml
requirements-test.txt

- fix for nightly build failures, similar to PR in responsible-ai-toolbox repo:
https://github.com/microsoft/responsible-ai-toolbox/pull/1257
failures are due to pywinpty dependency release failing in python 3.6
related issue:
https://github.com/spyder-ide/pywinpty/issues/218

fix windows nightly build failures due to pywinpty dependency failing in python 3.6

---

python/docs/conf.py
requirements-doc.txt

Some of the methods and classes were missing in the sphinx generated documentation due to some errors in the intersphinx mapping and dependencies.  This PR resolves those documentation issues.
How I validated: I changed the latest readthedocs build to point to this branch, and then validated that the documentation was finally building.  I switched the branch back to master branch.

fix some methods and classes missing from readthedocs documentation

---

python/interpret_community/permutation/permutation_importance.py

use the new WrappedTensorflowModel from ml_wrappers to handle tensorflow models>=2.6 in PFI, similar to pytorch models

fix PFI handling tensorflow models for tensorflow>=2.6

---

requirements-test.txt

Gated builds are failing recently with the error:
```
File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/dash/dash.py", line 17, in <module>
import flask
File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jinja2/__init__.py)
```
This PR resolves the issue by pinning jinja2 to older version.  The alternative is to upgrade flask, but this is currently not possible due to upstream environments using older versions of flask.

fix jinja2 build error with old version of flask by pinning jinja2

---

requirements-test.txt
tests/common_tabular_tests.py
tests/conftest.py
tests/mlflow/test_mlflow.py
tests/raw_explain/test_data_mapper.py
tests/raw_explain/test_feat_mappers.py
tests/raw_explain/test_raw_explanation.py
tests/test_does_quack.py
tests/test_error_handling.py
tests/test_explain_model.py
tests/test_explanation_adapter.py
tests/test_explanation_dashboard.py
tests/test_explanation_utils.py
tests/test_lime_explainer.py
tests/test_mimic_explainer.py
tests/test_misc_explainers.py
tests/test_notebooks.py
tests/test_pfi_explainer.py
tests/test_serialization_utils.py
tests/test_serialize_explainer.py
tests/test_serialize_explanation.py
tests/test_validate_explanations.py

Add flake8-pytest-style to linting

---

python/interpret_community/explanation/explanation.py
python/interpret_community/lime/lime_explainer.py
tests/common_tabular_tests.py
tests/test_mimic_explainer.py

Fix aggregating sparse multiclass explanations to global in global-only streaming with batches mode.
In the case that the explanations are
1.) computed on sparse multiclass data, and
2.) we set parameters to only compute the global explanation from local importance values, and
3.) we are using specifically the streaming aggregation from batches mode
(notice a lot of specific cases there), the logic currently fails as it is not designed to handle a list of sparse matrices.  The logic for this scenario is implemented in this PR and a test is added.

fix aggregating sparse multiclass explanations to global in global-only streaming with batches mode

---

README.md
python/docs/conf.py
python/docs/importances.rst
python/docs/index.rst
python/docs/overview.rst
python/docs/transformations.rst
python/docs/usage.rst
python/docs/visualizations.rst

Improve the documentation and readme website by reducing the size of the readme (and just having a general overview) and moving the sections to the website:
1.) Using interpret-community to create an explainer
2.) Local and global importance values - information about them and the APIs to compute them
3.) Raw and Engineered explanations
4.) The visualization dashboard in responsible-ai-toolbox
Note: I temporarily moved the 'latest' build in readthedocs to this branch so it would be easier to review the correctness of the changes.

improve readme by only leaving high-level overview and move more sections to the website with more details

---

README.md
python/README.md
python/docs/_static/theme_overrides.css
python/docs/conf.py
python/docs/contributing.rst
python/docs/explainers.rst
python/docs/importances.rst
python/docs/index.rst
python/docs/usage.rst
python/docs/visualizations.rst

More improvements to the interpret-community website, including:
- Added a contributing and code formatting guide (resolves user issue https://github.com/interpretml/interpret-community/issues/521)
- Added LIME explainer to list of supported explainers
- Fixed responsible-ai-toolbox link
- Fixed width/size of several tables in the website, so they would be more readable
Note: I temporarily moved the 'latest' build in readthedocs to this branch so it would be easier to review the correctness of the changes.

add more documentation to interpret-community website, including a contributing guide

---

requirements-dev.txt

Fix the gated build in interpret-community repository failing due to latest protobuf being incompatible with the version of tensorflow<2.5 used in interpret-community tests.  We pin to protobuf<4 to resolve the issue.

fix gated build due to protobuf dependency error

---

.github/workflows/CI-python.yml
.github/workflows/Code-Scan.yml
.github/workflows/python-linting.yml
README.md
devops/Code-Coverage.yml
devops/PR-Gate.yml
devops/README.md
devops/nightly.yml
docs/release-process.md
python/docs/notebooks.rst
python/docs/visualizations.rst

The master branch has been renamed to main in interpret-community, which is now the standard name used for github projects (due to fairness related issues).  This PR fixes related build scripts and links to point to the main branch.

rename master branch to main in interpret-community

---

python/interpret_community/common/constants.py
python/interpret_community/mimic/mimic_explainer.py
tests/test_mimic_explainer.py

Customers reported an issue where they were seeing all zero importance values when using mimic explainer with lightgbm surrogate model on very small data, with just 12 instances:
This PR sets the min_data_in_leaf parameter on the lightgbm surrogate model to 1 when very small data is detected in mimic explainer in order to resolve the issue by avoiding building a tree with one node and constant output due to the lack of data:
Note: build is failing for this PR right now due to protobuf dependency issue, which is fixed in the separate PR:
https://github.com/interpretml/interpret-community/pull/524

fix zero importances for very small data when using mimic explainer with lightgbm surrogate model

---

python/interpret_community/version.py

* Update github action for checkout, upload-artifact and setup-python from version 2 to 3 by @gaugup in https://github.com/interpretml/interpret-community/pull/515
* Add flake8-pytest-style to linting by @gaugup in https://github.com/interpretml/interpret-community/pull/512
* Improve the documentation website for interpret-community and update the main readme by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/518
* fix aggregating sparse multiclass explanations to global in global-only streaming with batches mode by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/519
* improve readme by only leaving high-level overview and move more sections to the website with more details by @imatiach-msft in …

release interpret-community v0.26.0

---

python/setup.py
requirements.txt

This PR updates interpret-community to support the new latest shap 0.41.0 package, which was just released several weeks ago.

upgrade interpret-community to new shap 0.41.0 release

---

python/interpret_community/tabular_explainer.py
requirements-test.txt
tests/common_tabular_tests.py
tests/test_does_quack.py
tests/test_explain_model.py
tests/test_logging.py
tests/test_serialize_explanation.py
tests/test_validate_explanations.py

The new version of flake8 package is incompatible with the old versions of flake8-bugbear 21.11.29 and old flake8-logging-format 0.6.0.  See related issue:
https://github.com/globality-corp/flake8-logging-format/issues/35
The fix here is to remove the pin on these packages so that we always get the latest versions.  
Specifically for bugbear the error shown is:
```
(flake) PS C:\interpret-community> flake8 --max-line-length=119
Traceback (most recent call last):
File "C:\Users\ilmat\Miniconda3\envs\flake\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\ilmat\Miniconda3\envs\flake\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\ilmat\Miniconda3\envs\flake\Scripts\flake8.exe\__main__.py", line 7, in <module>
File …
```

fix gated build failures due to incompatibility with new flake8 and old flake8-bugbear and old flake8-logging-format

---

notebooks/captum-integration-example.ipynb
python/interpret_community/_internal/raw_explain/raw_explain_utils.py
python/interpret_community/adapter/explanation_adapter.py
python/interpret_community/common/blackbox_explainer.py
python/interpret_community/dataset/decorator.py
python/interpret_community/explanation/explanation.py
python/interpret_community/explanation/serialization.py
python/interpret_community/lime/lime_explainer.py
python/interpret_community/mimic/mimic_explainer.py
python/interpret_community/shap/gpu_kernel_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py
tests/explanation_utils.py
tests/test_explanation_adapter.py

While adding tests in explanation adapter to improve code coverage, I found an error when include_local=False which is fixed in this PR.  The issue was that we called create_local in streaming mode, but the adapter does not have this method to compute importance values on the fly, and in fact we should just be aggregating the already computed local explanation instead.
Also, this PR moves the DatasetWrapper import to use ml_wrappers directly instead.

fix explanation adapter error when include_local=False and add tests

---

devops/templates/create-env-step-template.yml

Nightly build is failing with error output:
```
Requirement already satisfied: pip in c:\miniconda\envs\interp_community\lib\site-packages (22.1.2)
Collecting pip
Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
---------------------------------------- 2.0/2.0 MB 18.7 MB/s eta 0:00:00
ERROR: To modify pip, please run the following command:
C:\Miniconda\envs\interp_community\python.exe -m pip install --upgrade pip --user
```
This PR fixes the error by adding ```python -m``` call prior to pip install command.

fix nightly build failure on windows when installing pip

---

.github/workflows/CI-python.yml
.github/workflows/Code-Scan.yml
.github/workflows/python-linting.yml

Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>

Add scheduled builds

---

.github/workflows/CI-python.yml
devops/templates/test-run-step-template.yml
requirements-vis.txt

Temporary fix by installing rai-core-flask 0.5.0 directly to bypass nightly build failures on macos due to gevent/greenlet install errors caused by old pins in rai-core-flask 0.4.0.

temporary fix for nightly build in interpret-community

---

devops/PyPI-Release.yml

Update the pypi release pipeline to use python 3.7 since python 3.6 is no longer supported by default on ubuntu-latest image.  See pypi release error:
https://dev.azure.com/responsibleai/interpret-community/_build/results?buildId=15569&view=logs&j=28f19d9f-f9b2-5f7b-fd26-56c3feda2482&t=93dc4bf1-918f-5b9b-51e8-fb4711dda089

update interpret-community pypi release pipeline to use python 3.7

---

.github/workflows/CI-python.yml
tests/common_utils.py
tests/test_mimic_explainer.py
tests/test_pfi_explainer.py
tests/test_serialize_explainer.py

Recently started seeing gated build failures with the error:
```
2023-07-10T03:26:24.2325334Z         if one_alpha:
2023-07-10T03:26:24.2325569Z             A.flat[:: n_features + 1] += alpha[0]
2023-07-10T03:26:24.2325960Z >           return linalg.solve(A, Xy, sym_pos=True, overwrite_a=True).T
2023-07-10T03:26:24.2326366Z E           TypeError: solve() got an unexpected keyword argument 'sym_pos'
```
link to build:
https://[pipelines.actions.githubusercontent.com/serviceHosts/c1806717-186f-43d1-b5bb-864035754060/_apis/pipelines/1/runs/1609/signedlogcontent/2?urlExpires=2023-07-10T15%3A33%3A11.6111338Z&urlSigningMethod=HMACV1&urlSignature=5aCYsNh0b1aoNRoesrWhta7mxH8IrH5Crdw%2BgiVPGtI%3D](https://pipelines.actions.githubusercontent.com/serviceHosts/c1806717-186f-43d1-b5bb-864035754060/_api …

fix sklearn build error due to old dependency version installed with newer scipy

---

python/interpret_community/mimic/mimic_explainer.py

The doc for the private _load method (not public since it has limited support only for LightGBM surrogate models) is confusing because it refers to the original model as an ONNX model when it doesn't necessarily need to be.  This PR cleans up the method doc to limit confusion and provide more information.

clean up load method API doc for mimic explainer to reduce confusion

---

python/interpret_community/mimic/models/lightgbm_model.py

Gated builds seem to be failing due to error when calling inspect.getargspec in tests:
```
2023-07-18T22:15:32.9356507Z         if kwonlyargs or ann:
2023-07-18T22:15:32.9356904Z >           raise ValueError("Function has keyword-only parameters or annotations"
2023-07-18T22:15:32.9357273Z                              ", use inspect.signature() API which can support them")
2023-07-18T22:15:32.9358074Z E           ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
```
See build:
https://[pipelines.actions.githubusercontent.com/serviceHosts/c1806717-186f-43d1-b5bb-864035754060/_apis/pipelines/1/runs/1655/signedlogcontent/3?urlExpires=2023-07-19T13%3A49%3A56.8756087Z&urlSigningMethod=HMACV1&urlSignature=n7yT0tLu9c5kxVKqapcs71ABV …

fix gated builds due to getargspec deprecation

---

.readthedocs.yaml

The API reference docs stopped building with the 0.29.0 release.  It looks like this is due to the removal of the requirements.txt file at the top level.  Currently the builds are failing with the error:
```
WARNING: autodoc: failed to import module 'interpret_community'; the following exception was raised:
No module named 'numpy'
```
This PR fixes the issue through the recommendation here to install the package directly in the builds in the config:
https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install
Another option may be to bring back the top-level requirements.txt file but it seems it is unnecessary.

fix auto-generated API sphinx docs build for interpret-community

---

.github/workflows/python-linting.yml
requirements-linting.txt
requirements-test.txt

Looks like the linting workflow doesn't require other dependencies like jupyter, papermill etc.

Create requirements-linting.txt to separate linting dependencies

---

python/interpret_community/explanation/explanation.py

In previous PR we bumped the version of interpret-core:
https://github.com/interpretml/interpret-community/pull/573
As part of that PR, I had to modify the namespace of the helper functions imported from interpret-core due to a breaking change from that package.
I reviewed the merged changes and realized I could add a try/catch to make interpret-community backwards compatible with older versions of interpret-core, in case there was some reason this was needed.

backcompat imports to work with older versions of interpret-core

---

.readthedocs.yaml
python/docs/conf.py
requirements-doc.txt

The interpret-community docs build started failing with errors because html_theme has become mandatory (I'm not exactly sure why, since sphinx is pinned - perhaps another package it depends on was updated?):
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/interpret-community/envs/v0.30.0/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
exec(code, namespace)
File "/home/docs/checkouts/readthedocs.org/user_builds/interpret-community/checkouts/v0.30.0/python/docs/conf.py", line 152, in <module>
'html_theme': html_theme,
NameError: name 'html_theme' is not defined
```
Specifying the html_theme in this PR to resolve the sphinx doc build errors.
Also updating sphinx package to latest.
Link to passing build: …

fix interpret-community sphinx docs build failures by specifying html_theme

---

.github/workflows/CI-python.yml
devops/templates/test-run-step-template.yml
tests/test_explain_model.py
tests/test_validate_explanations.py

Seeing nightly build failures in interpret-community package for latest v2.0.0 xgboost models (just recently released to pypi).  This error is already fixed in latest shap but when we install responsibleai package, the econml package downgrades shap because it is pinned to an older version.  This PR undoes the pin temporarily in the builds to install latest shap which resolves the test failures.
Build failure link:
https://dev.azure.com/responsibleai/interpret-community/_build/results?buildId=16869&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=9dfda548-ca11-5cc8-5a69-382ee7f1c50a
Build failure error:
```
if self.feature_perturbation == "tree_path_dependent" and self.model.model_type != "internal" and self.data is None:
model_output_vals = None
phi = None
if self.model.model_type == …
```

fix failing xgboost tests in nightly build by upgrading to latest shap, which is getting pinned by econml->responsibleai to older version

---

requirements-dev.txt

Looks like recent tensorflow release is incompatible with numpy. 
```
from tensorflow.python.saved_model import saved_model
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/tensorflow/python/saved_model/saved_model.py:20: in <module>
from tensorflow.python.saved_model import builder
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/tensorflow/python/saved_model/builder.py:23: in <module>
from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
/usr/share/miniconda/envs/test/lib/python3.9/site-packages/tensorflow/python/saved_model/builder_impl.py:[26](https://github.com/interpretml/interpret-community/actions/runs/6347561980/job/17242731392#step:12:27): in <module>
from tensorflow.python.framework import dtypes …
```

Update requirements-dev.txt to pin tensorflow below 2.14.0

---

.github/workflows/CI-python.yml
devops/templates/create-env-step-template.yml
python/docs/overview.rst
requirements-test.txt

fix gated build failures in interpret-community due to captum installation issues from conda
Getting errors in gated builds:
```
ImportError while importing test module '/Users/runner/work/1/s/tests/test_explanation_adapter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/miniconda/envs/interp_community/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/test_explanation_adapter.py:9: in <module>
from captum.attr import IntegratedGradients
E   ModuleNotFoundError: No module named 'captum'
```
We were seeing similar errors in the https://github.com/microsoft/responsible-ai-toolbox repository and a similar fix was applied there to move captum to pip install after a new …

fix gated build failures in interpret-community due to captum installation issues from conda

---

.github/workflows/CI-python.yml
devops/templates/test-run-step-template.yml
python/setup.py

update interpret-community to shap 0.44.0 which was released on Dec 7, 2023:
https://pypi.org/project/shap/#history

update interpret-community to shap 0.44.0

---

devops/PR-Gate.yml
python/setup.py

update interpret-community package to interpret 0.5.0, ml-wrappers 0.5.4
Update: it looks like interpret-core has removed the "required" extra with 0.5.0, see:
https://github.com/interpretml/interpret/commit/ee37ca1902d034c2bc5e5aed113c8d46a300d59a#diff-7a456cafef94c199eaa08821e95e9c72394da4be21fcfc965ec8b29170c9c2e8
Hence, removing it from this PR now - otherwise the install process gives an error.

update interpret to 0.5.0, ml-wrappers to 0.5.4

---

python/interpret_community/version.py

* Add `flake8-all-not-strings` to linting by @gaugup in https://github.com/interpretml/interpret-community/pull/576
* fix interpret-community sphinx docs build failures by specifying html_theme by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/578
* update interpret-community to shap 0.42.1 and ml-wrappers 0.5.1 by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/579
* fix failing xgboost tests in nightly build by upgrading to latest shap, which is getting pinned by econml->responsibleai to older version by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/580
* update interpret to 0.4.4, ml-wrappers to 0.5.2 and enable fixed pfi test by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/582 …

release interpret-community v0.31.0

---

.github/workflows/CI-python.yml
.github/workflows/release-interpret-community.yml
python/setup.py
requirements-dev.txt
requirements-test.txt

update interpret-community to python 3.9 by default and fix some test failures in gated builds
Copilot summary:
This pull request focuses on updating the supported Python versions in the CI workflows and the package metadata. The most important changes include removing support for Python 3.7 and 3.8 and standardizing on Python 3.9.
Updates to CI workflows:
* [`.github/workflows/CI-python.yml`](diffhunk://#diff-2b75812bc12c9a72b073df40c11ceda4af97cc64083831530ca88c683447b387L17-R17): Removed Python 3.7 and 3.8 from the `matrix` configuration, now only testing with Python 3.9. Updated conditions for uploading code coverage results, retrying uploads, and setting codecov status to use Python 3.9 instead of 3.8. [[1]](diffhunk://#diff-2b75812bc12c9a72b073df40c11ceda4af97cc64083831530ca88c683447 …

update interpret-community to python 3.9 by default

---

.github/workflows/CI-python.yml
.github/workflows/release-interpret-community.yml
devops/templates/test-run-step-template.yml
python/interpret_community/adapter/explanation_adapter.py
python/interpret_community/common/explanation_utils.py
python/interpret_community/mimic/models/explainable_model.py
python/interpret_community/mimic/models/linear_model.py
python/interpret_community/mimic/models/tree_model_utils.py
python/interpret_community/shap/deep_explainer.py
python/interpret_community/shap/kernel_explainer.py
python/interpret_community/shap/linear_explainer.py
python/interpret_community/shap/tree_explainer.py
python/setup.py
tests/conftest.py
tests/test_validate_explanations.py

update interpret-community to shap 0.46.0
This includes fixes for major breaking change https://github.com/shap/shap/pull/3318 which broke all of the explainers and changed the dimensions/format from list of 2d np.ndarray
```
(# classes x # examples x # features)
```
to 3d np.ndarray
```
(# examples x # features x # classes)
```

update interpret-community to shap 0.46.0

---

.github/workflows/CI-python.yml
devops/templates/create-env-step-template.yml
python/interpret_community/common/explanation_utils.py
python/setup.py
requirements-dev.txt
tests/common_utils.py

update interpret-community to ml-wrappers 0.6.0
As part of this, support pandas>2.0 and update to latest interpret-core
Copilot summary:
This pull request includes several updates to dependencies and improvements to error handling and package installation processes. The most important changes are summarized below:
* Updated `ml-wrappers` to version `0.6.0` and `interpret-core` to version `0.6.9` in `python/setup.py`.
* Removed version constraint for `tensorflow` in `requirements-dev.txt`.
* Modified the Conda package installation commands in `devops/templates/create-env-step-template.yml` to enforce strict channel priority and ensure consistent package versions.
* Added checks to convert `absolute_error` and `error_sign` to numpy arrays if they are not already in …

update interpret-community to ml-wrappers 0.6.0
