- python/interpret_community/shap/deep_explainer.py
change pytorch missing message from info to debug
> change pytorch missing message from info to debug

- python/interpret_community/explanation/explanation.py
raw features missing is_raw property
> raw features missing is_raw property

- python/interpret_community/shap/linear_explainer.py
Should help fix the current issues with the other pandas PR
> missed this param on the first copy over

- python/interpret_community/mimic/mimic_explainer.py
- test/common_tabular_tests.py
fix mimic explainer missing initialization examples on output explanation
> fix mimic explainer missing initialization examples on output explanation

- python/interpret_community/shap/tree_explainer.py
fix pandas string test with tree explainer
seems one of the tests is failing in interpret-community CI
> fix pandas string test with tree explainer

- python/interpret_community/common/constants.py
- python/interpret_community/mimic/models/__init__.py
- python/interpret_community/mimic/models/lightgbm_model.py
- python/interpret_community/mimic/models/linear_model.py
- python/interpret_community/mimic/models/tree_model.py
- python/setup.py
- test/test_through_ext.py
moved explainable models under glassbox extension
> moved explainable models under glassbox extension

- python/setup.py
add missing required packaging dependency
> add missing required packaging dependency

- python/interpret_community/__init__.py
- python/interpret_community/common/aggregate.py
- python/interpret_community/common/base_explainer.py
- python/interpret_community/common/constants.py
- python/interpret_community/common/explanation_utils.py
- python/interpret_community/common/metrics.py
- python/interpret_community/community/__init__.py
- python/interpret_community/explanation/explanation.py
- python/interpret_community/shap/__init__.py
> minor doc updates

- python/interpret_community/explanation/explanation.py
fixed bug with raw explanations set to classification task instead of regression by default on deserialize
> fixed bug with raw explanations set to classification task instead of regression by default on deserialize

- .gitignore
- python/setup.py
> fixing pip install of package

- python/setup.py
release v0.1.0.1
- contains several minor bugfixes and fixes error on pip install
> release v0.1.0.1

- README.md
Many word updates:
- step by step
- badges for pipeline tests
- badges for azure notebooks and binder (may be removed later if widget does not work)
Even though this is a WIP, it is being put in as a PR for visibility.
> Initial update to Readme in new repo

- README.md
fix broken getting started link in readme
> fix broken getting started link in readme

- python/setup.py
release v0.1.0.2, add lower-bound pin of interpret package
> release v0.1.0.2, pin interpret

- python/interpret_community/explanation/explanation.py
fixing visualization widget and display issues with interpret
> fixing visualization widget and display issues with interpret

- README.md
Added intro, target audience, models...
> new readme updates

- test/test_mimic_explainer.py
disable test for pandas indexes
> disable test for pandas indexes

- python/README.md
> updated the readme for pypi

- python/interpret_community/permutation/permutation_importance.py
fix error in PFI if pytorch is not installed
fixes issue https://github.com/interpretml/interpret-community/issues/40
> fix error in PFI if pytorch is not installed

- python/interpret_community/widget/ExplanationDashboard.py
fix error in explanation dashboard when used with PFI
fixes issue https://github.com/interpretml/interpret-community/issues/42
> fix error in explanation dashboard when used with PFI

- python/setup.py
> release v0.1.0.3

- python/interpret_community/common/model_wrapper.py
- python/interpret_community/shap/deep_explainer.py
fix demo notebook for tensorflow
Note: this is still work in progress and not yet for checkin
> wip: fix demo notebook for tensorflow

- python/setup.py
> release v0.1.0.4

- README.md
This removes the azure nb and binder references.
> removed binder and azure nb references

- python/interpret_community/__init__.py
- python/interpret_community/common/chained_identity.py
need to use a separate file handler for logging, since basicConfig may already be set
> use handler for logging to file

- python/setup.py
update interpret dependency to 0.1.19
> update interpret dependency to 0.1.19

- README.md
- devops/README.md
- devops/mac-test.yml
- test/README.md
Many updates:
- fix doc issues
- update badges
- fix words
> Prep for release

- devops/PR-Gate.yml
The triggers were set in the devops UI. Something appears not to be quite working properly. This is to try an alternative method.
> update triggers in yml

- AUTHORS.md
adding maintainers and contributors
> adding maintainers and contributors

- python/setup.py
- requirements.txt
- test/test_explain_model.py
update shap to 0.31.0 for avanade customer bugfix that exists in latest shap
edit: 0.32.1
> update shap to 0.32.1

- python/setup.py
> release v0.2.0

- test/raw_explain/test_raw_explanation.py
add checks for fields in raw features explanation derived from engineered explanation
> add checks for fields in raw features explanation derived from engineered explanation

- test/test_explain_model.py
re-enabled test after shap version upgrade
fixes issue https://github.com/interpretml/interpret-community/issues/60
> re-enabled test after shap version upgrade

- python/interpret_community/common/constants.py
- python/interpret_community/dataset/dataset_wrapper.py
- python/interpret_community/explanation/explanation.py
- python/interpret_community/mimic/mimic_explainer.py
- python/interpret_community/permutation/permutation_importance.py
- python/interpret_community/shap/deep_explainer.py
- python/interpret_community/shap/kernel_explainer.py
- python/interpret_community/shap/linear_explainer.py
- python/interpret_community/shap/tree_explainer.py
- test/common_tabular_tests.py
- test/test_explain_model.py
Add information about dataset size to explanations. This will be follow up on in the Azure repo where this size info will be uploaded and used by the UI.
Remaining work on this PR: 
* move the repeated stuff to DatasetWrapper
* use a constant rather than the repeated string
> Dataset size

- notebooks/advanced-feature-transformations-explain-local.ipynb
- notebooks/explain-binary-classification-local.ipynb
- notebooks/explain-multiclass-classification-local.ipynb
- notebooks/explain-regression-local.ipynb
- notebooks/simple-feature-transformations-explain-local.ipynb
resolves issue https://github.com/interpretml/interpret-community/issues/50
> change wording for PFIExplainer in notebooks

- python/interpret_community/__init__.py
- test/test_logging.py
fix logging logic if directory for file is missing
> fix logging logic if directory for file is missing

- python/setup.py
> release v0.2.1

- python/interpret_community/common/constants.py
- python/interpret_community/explanation/explanation.py
partial fix to PFI display issue, adding metadata for single or multiclass explanation dimension
partial fix for: https://github.com/interpretml/interpret-community/issues/49
> partial fix to PFI display issue, adding metadata for single or multiclass explanation dimension

- python/interpret_community/common/constants.py
- python/interpret_community/mimic/models/linear_model.py
- python/interpret_community/shap/linear_explainer.py
fixes issue https://github.com/interpretml/interpret-community/issues/55
> fixed warning on linear explainer due to unspecified default value

- python/interpret_community/mimic/mimic_explainer.py
fixing breaking change by making features public again on mimic explainer
> fixing breaking change by making features public again on mimic explainer

- python/setup.py
> release v0.2.2

- python/setup.py
> release v0.2.3

- visualization/dashboard/package.json
- visualization/dashboard/src/MLIDashboard/Controls/FeatureImportance/FeatureImportanceBar.tsx
missing aria-label found by Accessibility Insights
> add aria-label to top k slider

- python/setup.py
- requirements.txt
shap is currently broken by 0.22
> pin sklearn

- python/setup.py
> release v0.3.0

- python/setup.py
> patch release v0.3.1

- python/interpret_community/explanation/explanation.py
Realized this param was completely unused, I'd added it without thinking
> remove num_examples param

- python/interpret_community/dataset/dataset_wrapper.py
- python/setup.py
- requirements.txt
- test/common_utils.py
- test/conftest.py
- test/test_explain_model.py
- test/test_mimic_explainer.py
updated tests and code to remove scikit-learn pin
> remove sklearn pin

- python/interpret_community/common/constants.py
- python/interpret_community/explanation/explanation.py
- test/test_does_quack.py
> add sections to does quack methods

- python/interpret_community/__init__.py
- test/test_logging.py
slightly changed env variable for logging for clarity
INTERPRETC_LOGS -> INTERPRET_C_LOGS
> slightly changed env variable for logging for clarity

- devops/PR-Gate.yml
- devops/mac-test.yml
- devops/nightly.yml
- devops/notebook.yml
- devops/win-test.yml
fix pipeline step name
use interpret-community instead of interpret-extensions (the previous name)
> fix pipeline step name

- python/setup.py
> release 0.4.0

- devops/PR-Gate.yml
- devops/notebook.yml
- devops/templates/create-env-template.yml
- test/pytest.ini
- test/test_notebooks.py
Add papermill for notebook testing. 
This provides step 1 in #132
> add papermill to test nb

- python/interpret_community/mimic/models/explainable_model.py
- python/interpret_community/mimic/models/linear_model.py
- python/interpret_community/mimic/models/tree_model.py
> fix sphinx warnings

- python/setup.py
> release v0.4.1

- README.md
Update ExplanationDashboard param in the readme
> Update ExplanationDashboard param in the readme

- python/interpret_community/common/blackbox_explainer.py
changed info message to debug for regression models explained by blackbox explainers
> changed info message to debug for regression models explained by blackbox explainers

- python/setup.py
- Removed tabindex from GridChart 
- Flask service for visualization dashboard
- Accessibility updates for visualization dashboard
- minor change of info message to debug for regression models explained by blackbox explainers
> release v0.5.0

- python/setup.py
patch release v0.5.1
fixes visualization dashboard failing to visualize after previous release
> release v0.5.1

- devops/notebook.yml
- requirements.txt
enabling notebook build on master
> enabling notebook build on master

- devops/PR-Gate.yml
saving the pip freeze output file to artifacts for debugging purposes on builds
> added pip freeze file to artifacts

- notebooks/explain-regression-local.ipynb
- test/test_notebooks.py
added scrapbook tests to notebooks
> added scrapbook tests to notebooks

- test/test_notebooks.py
add cell validation to each notebook
> add cell validation to each notebook

- python/interpret_community/common/error_handling.py
- python/interpret_community/widget/explanation_dashboard_input.py
improve error handling in widget to propagate inner exception and stack trace
useful for debugging user issues
> improve error handling in widget to propagate inner exception and stack trace

- python/setup.py
updated shap to 0.34.0 and interpret-core to 0.1.20
> updated shap and interpret-core

- python/setup.py
release v0.6.0
- updated shap and interpret-core dependencies
- support timeseries models
- address accessibility bugs
- improve error handling in widget to propagate inner exception and stack trace
- notebook test infrastructure improvements
> release v0.6.0

- test/test_explain_model.py
validates issue to be fixed in https://github.com/slundberg/shap/pull/1046
> add xgboost test for binary classification case with TreeExplainer

- python/docs/conf.py
Thanks to Marc Gelormino for the suggestions
> update sphinx conf file

- python/interpret_community/widget/explanation_dashboard.py
fix notebook failures due to ports in use from previous notebooks, add automatic port scan mechanism by default
> fix notebook failures due to ports in use from previous notebooks, add automatic port scan mechanism by default

- python/interpret_community/widget/explanation_dashboard.py
fix typo causing explanation dashboard failure in databricks
> fix typo causing explanation dashboard failure in databricks

- python/interpret_community/common/model_wrapper.py
- python/interpret_community/permutation/permutation_importance.py
fix logger causing failure if pytorch not installed
> fix logger causing failure if pytorch not installed

- python/interpret_community/widget/explanation_dashboard.py
fix port not assigned issue
port was not assigned so that by default notebook tests passed but javascript failed to load when using None for port
> fix port not assigned issue

- python/interpret_community/common/error_handling.py
- python/interpret_community/widget/explanation_dashboard_input.py
- python/interpret_community/widget/js/package.json
- python/interpret_community/widget/js/yarn.lock
- test/test_notebooks.py
- visualization/dashboard/package.json
- visualization/dashboard/src/MLIDashboard/Controls/FeatureImportance/Beenhive.tsx
- visualization/dashboard/src/MLIDashboard/Controls/Scatter/ScatterUtils.ts
- visualization/dashboard/src/MLIDashboard/ExplanationDashboard.tsx
- visualization/dashboard/src/MLIDashboard/SharedComponents/BarChart.tsx
- visualization/dashboard/yarn.lock
- visualization/test/test-page/App.jsx
- visualization/test/test-page/yarn.lock
The dashboard seems to fail if the class or feature dimensions are inconsistent. It seems most likely to occur if the user uploads a class or feature name vector that disagrees with the underlying data.
> Resilient to inconsistently shaped input data

- python/setup.py
release v0.7.0
- python doc updates
- fix notebook failures due to ports in use from previous notebooks, add automatic port scan mechanism by default
- fix typo causing explanation dashboard failure in databricks
- fix logger causing failure if pytorch not installed
- changed plotly chart table to have display block
- fix port not assigned issue
- improved gevent error message
- initialize icons once, fix exceptions if empty object passed in
- resilience to inconsistently shaped input data
> release v0.7.0

- python/interpret_community/explanation/explanation.py
- python/interpret_community/mimic/mimic_explainer.py
- python/interpret_community/mimic/models/linear_model.py
- test/test_mimic_explainer.py
adding full e2e sparse linear surrogate model support
> adding sparse linear surrogate model support

- python/interpret_community/explanation/explanation.py
fix num classes sparse handling (used by explanation client)
EDIT: also fixes local explanation feature importance values for multiclass case
> fix num classes sparse handling

- python/interpret_community/common/explanation_utils.py
- python/interpret_community/explanation/explanation.py
- python/interpret_community/mimic/mimic_explainer.py
- test/common_tabular_tests.py
- test/common_utils.py
- test/conftest.py
- test/raw_explain/test_raw_explanation.py
added sparse local importance values aggregation logic from engineered to raw features
> added sparse local importance values aggregation logic from engineered to raw features

- python/setup.py
- added full e2e sparse linear surrogate model support
- localize dashboard and widget
- fix num classes sparse handling
-  added sparse local importance values aggregation logic from engineered to raw features
> release v0.8.0

- python/interpret_community/common/constants.py
- python/interpret_community/explanation/explanation.py
- test/test_does_quack.py
fix does quack for sparse local importance values
> fix does quack for sparse local importance values

- python/setup.py
- validate inputs in dashboard
- fix does quack for sparse local importance values
> patch release v0.8.1

- python/interpret_community/common/model_wrapper.py
- test/common_utils.py
- test/test_serialize_explainer.py
fix save for inner explainer and wrapped model in kernel explainer
> fix save for inner explainer and wrapped model in kernel explainer

- python/setup.py
- make sure all data is returned as a list from explanation
- fix save for inner explainer and wrapped model in kernel explainer
- fix aggregation logic to use mean
> patch release v0.8.2

- python/setup.py
- make sure all data is returned as a list from explanation
- fix save for inner explainer and wrapped model in kernel explainer
- fix aggregation logic to use mean
> release 0.9.0

- python/interpret_community/mimic/models/explainable_model.py
- python/interpret_community/mimic/models/lightgbm_model.py
> fix doc build errors

- python/setup.py
> patch release v0.9.1

- python/interpret_community/mimic/mimic_explainer.py
- python/interpret_community/mimic/models/lightgbm_model.py
- python/interpret_community/mimic/models/linear_model.py
- python/interpret_community/mimic/models/tree_model.py
- test/raw_explain/test_raw_explanation.py
- test/test_mimic_explainer.py
fix mimic method to mention the surrogate model type
> fix mimic method to mention the surrogate model type

- python/interpret_community/explanation/explanation.py
another fix for doc build due to missing docs on properties
> another fix for doc build due to missing docs on properties

- python/setup.py
- another fix for doc build due to missing docs on properties
- fix mimic method to mention the surrogate model type
> patch release v0.9.2

- python/setup.py
updated interpret-core to 0.1.21
> updated interpret-core to 0.1.21

- docs/release-process.md
added release docs for interpret-community
> added release docs for interpret-community

- python/docs/conf.py
- python/docs/index.rst
- python/interpret_community/common/model_wrapper.py
- python/interpret_community/community/__init__.py
- requirements.txt
several fixes for sphinx doc, required for the readthedocs documentation website:
https://interpret-community.readthedocs.io/en/latest/
> several fixes for sphinx doc

- python/setup.py
* Dashboard auto focus update
* Bugfix for sparse data on when using MimicExplainer with a linear surrogate for binary classification
* Set up port forwarding so that the dashboard can be shown in Azure environments
* Bugfix for true ys that aren't lists
> release v0.10.2

- python/setup.py
* v2 version of the dashboard has been added!
* theme improvement for sphinx API documentation
* improvement for port handling within the dashboard
* improvement to scipy sparse import syntax
> release v0.11.0

- test/models.py
- test/test_mimic_explainer.py
- test/test_serialize_explainer.py
fix build break due to scikit-learn update
> fix build break due to scikit-learn update

- python/interpret_community/shap/tree_explainer.py
- test/test_explain_model.py
added temporary workaround for binary XGBoost with TreeExplainer
> added temporary workaround for binary XGBoost with TreeExplainer

- python/setup.py
* add support for passing in a theme object to the dashboard
* fixes for the latest version of scikit-learn
* improve warning/error messaging in the dashboard
* optimize `get_ranked_per_class_names()` memory usage
* improve PFI error messaging
* improvements to documentation
> release v0.11.1

- python/setup.py
* Cohort functionality added to the dashboard
* Improvement in PFI behavior when passing true_labels as a kwarg
* Improve type handling in the list sorting util
> release v0.11.2

- AUTHORS.md
* adding my name to the author list although i wasn't sure which section. Let me know if you want me to move it around! 
@imatiach-msft
> update author.md 

- python/setup.py
Explanation dashboard v2 is now the default experience!
> release v0.13.0

- python/interpret_community/__init__.py
SDK
- MLflow `log_model`-based implementations of `log_explanation` and `get_explanation`
Dashboard
- update to categorical handling
- rework internals so hotkeys work better in Jupyter notebooks
Internal
- lots of updates to test pipelines
- README improvements
> release v0.14.0

- python/interpret_community/__init__.py
SDK:
- improvements to docstrings/error messages around large datasets
Viz:
- added support for passing errors out of the dashboard for hosts to work with
Testing:
- improved notebook tests
- removed deprecated test pipelines
- added pypi release pipeline (trying it out for this release)
> release v0.14.1

- python/setup.py
add ipython as a dependency to the visualization extra
resolves issue:
https://github.com/MicrosoftDocs/azure-docs/pull/58411
> add ipython as a dependency to the visualization extra

- devops/templates/create-env-step-template.yml
fix windows nightly build timing out in conda list
Some related issues for context:
https://github.com/conda/conda/issues/9141
Seems latest conda has this fixed, hopefully the nightly will be green now.
> fix windows nightly build timing out in conda list

- python/setup.py
update dependency on interpret-core to latest 0.2.1
> update dependency on interpret-core to latest 0.2.1

- python/interpret_community/__init__.py
release interpret-community v0.14.2
- Categorical cohort fix for explanation dashboard
- String class labels fix with mimic explainer
- Add ipython as a dependency to visualization extra
- Fixed credentialed POST requests for predictions in dashboard (tested in notebook VM), and added support for remote VM with public IP
- Fix for job retries in pipelines
> release interpret-community v0.14.2

- python/interpret_community/widget/explanation_dashboard.py
fix "open in new tab" scenario for ExplanationDashboard in DSVM environment
fixes issue https://github.com/interpretml/interpret-community/issues/308
> fix "open in new tab" scenario for ExplanationDashboard in DSVM environment

- python/interpret_community/widget/explanation_dashboard.py
> update CDN path for widget

- test/test_mimic_explainer.py
add mimic explainer test for high-dimensional dense raw features explanation
this validates that the issue where get_raw_feat_importances ran into OOM error is fixed with another recent PR
https://github.com/interpretml/interpret-community/pull/313
> add mimic explainer test for high-dimensional dense raw features explanation

- python/interpret_community/mimic/models/lightgbm_model.py
- test/test_mimic_explainer.py
fix lightgbm 3.0 support by densifying input matrix to reenable tests
> fix lightgbm 3.0 support by densifying input matrix to reenable tests

- python/interpret_community/version.py
- remove visualization directory as it is being moved to a common respository
- update tests to support lightgbm 3.0 update
- optimize data mapper memory usage
- update CDN path for widget
-  add mimic explainer test for high-dimensional dense raw features explanation
- fix lightgbm 3.0 support by densifying input matrix to reenable tests
-  fix issues with importing version in setup.py before dependencies installed
> release interpret-community v0.15.0

- python/docs/conf.py
this change should make it easier to automate sphinx doc updates
> reuse version in sphinx build

- python/interpret_community/version.py
- add eval_data to get_raw_explanation
- remove use_cdn from explanation dashboard
- fix credentialed VM response data when using axios library
- reuse version in sphinx build
> release interpret-community 0.15.2

- python/interpret_community/explanation/explanation.py
- python/interpret_community/widget/explanation_dashboard.py
- test/datasets.py
- test/test_explanation_dashboard.py
Fix explanation dashboard json serialization issue
Fixes customer issue with ExplanationDashboard not rendering due to json error caused by datetime values in the raw dataset
> Fix explanation dashboard json serialization issue

- python/interpret_community/explanation/explanation.py
- test/test_mimic_explainer.py
> Fix number of features for raw explanations when using LinearExplainableModel

- test/test_logging.py
fixed build error due to env variable persisting
> fixed build error due to env variable persisting

- python/interpret_community/version.py
Release notes:-
- Fix number of features for raw explanations when using LinearExplainableModel
- Fix explanation dashboard json serialization issue
> release interpret-community 0.15.4

- test/test_error_handling.py
> Add unit test for error_handling.py

- test/test_validate_explanations.py
> Use ndcg from metrics in test_validate_explanations.py

- test/test_mimic_explainer.py
- test/test_serialize_explainer.py
> Consolidate MimicExplainer serialization tests

- devops/templates/create-env-step-template.yml
- requirements.txt
add setuptools upgrade to env setup script prior to pip install command
> add setuptools upgrade to env setup script prior to pip install command

- README.md
- devops/templates/create-env-step-template.yml
- devops/templates/test-run-step-template.yml
- notebooks/advanced-feature-transformations-explain-local.ipynb
- notebooks/explain-binary-classification-local.ipynb
- notebooks/explain-multiclass-classification-local.ipynb
- notebooks/explain-regression-local.ipynb
- notebooks/simple-feature-transformations-explain-local.ipynb
- python/interpret_community/shap/deep_explainer.py
- python/interpret_community/widget/explanation_dashboard.py
- requirements-dev.txt
- requirements-test.txt
- requirements-vis.txt
- requirements.txt
- test/test_misc_explainers.py
- test/test_notebooks.py
- add deprecation message for the old dashboard
- use the new ExplanationDashboard from the raiwidgets package
> add deprecation message for old dashboard, add new raiwidgets dashboard to notebooks

- python/interpret_community/version.py
Release notes:-
- upgrade setuptools to latest to fix pypi upload error 
- add setuptools upgrade to env setup script prior to pip install command 
- update to interpret-core 0.2.4 
- Support y_pred as pandas DataFrame for surrogate model predictions 
- add deprecation message for old dashboard, add new raiwidgets dashboard to notebooks 
- fix load explanation methods for numpy based variables 
> release interpret-community 0.17.0

- devops/templates/create-env-step-template.yml
- devops/templates/package-installation-step-template.yml
- devops/templates/test-run-step-template.yml
- requirements-vis.txt
- test/test_explanation_dashboard.py
fix nightly build issues related to gevent/greenlet dependencies
> fix nightly build issues

- python/interpret_community/_internal/raw_explain/data_mapper.py
- python/interpret_community/_internal/raw_explain/data_mapper_utils.py
- python/interpret_community/_internal/raw_explain/feature_mappers.py
- python/interpret_community/_internal/raw_explain/raw_explain_utils.py
- python/interpret_community/common/aggregate.py
- python/interpret_community/common/blackbox_explainer.py
- python/interpret_community/common/constants.py
- python/interpret_community/common/explanation_utils.py
- python/interpret_community/common/model_wrapper.py
- python/interpret_community/common/structured_model_explainer.py
- python/interpret_community/dataset/dataset_wrapper.py
- python/interpret_community/explanation/explanation.py
- python/interpret_community/lime/lime_explainer.py
- python/interpret_community/mimic/mimic_explainer.py
- python/interpret_community/mimic/models/explainable_model.py
- python/interpret_community/mimic/models/lightgbm_model.py
- python/interpret_community/mimic/models/linear_model.py
- python/interpret_community/mimic/models/tree_model.py
- python/interpret_community/mimic/models/tree_model_utils.py
- python/interpret_community/permutation/permutation_importance.py
- python/interpret_community/shap/deep_explainer.py
- python/interpret_community/shap/kernel_explainer.py
- python/interpret_community/shap/linear_explainer.py
- python/interpret_community/shap/tree_explainer.py
- python/interpret_community/tabular_explainer.py
fix various sphinx doc warnings from libraries referencing interpret-community
> fix sphinx doc warnings

- python/interpret_community/explanation/explanation.py
- test/test_explanation_dashboard.py
Adds missing 'intercept' field on local explanation 'mli' data.
Resolves issues: https://github.com/microsoft/responsible-ai-widgets/issues/367 https://github.com/interpretml/interpret-community/issues/260
> fix issues with visualizing local explanation

- test/test_serialization_utils.py
> Add test case of serializing pandas timestamp

- python/interpret_community/mimic/models/lightgbm_model.py
Note: this is using sparse logic added to lightgbm after 3.1.0 release
for lightgbm surrogate model in mimic explainer, if input data is sparse call predict directly instead of using shap TreeExplainer, which doesn't have sparse logic implemented yet
note: existing tests already validate sparse logic works correctly
> add sparse feature importance support for lightgbm surrogate model

- python/interpret_community/common/explanation_utils.py
- python/interpret_community/common/model_wrapper.py
- python/interpret_community/dataset/dataset_wrapper.py
- python/interpret_community/explanation/explanation.py
- python/interpret_community/lime/lime_explainer.py
- python/interpret_community/mimic/mimic_explainer.py
- python/interpret_community/mimic/models/linear_model.py
- python/setup.py
- requirements-dev.txt
- requirements-vis.txt
- requirements.txt
- test/test_explain_model.py
- test/test_misc_explainers.py
- test/test_serialize_explanation.py
upgrade shap to 0.39.0
- officially add python 3.8 support and remove python 3.5 support
> upgrade shap to 0.39.0

- python/interpret_community/_internal/raw_explain/feature_mappers.py
- test/datasets.py
- test/test_explain_model.py
add support for drop parameter in one hot encoder mapper
resolves issue: https://github.com/interpretml/interpret-community/issues/403
> add support for drop parameter in one hot encoder mapper

- devops/templates/create-env-step-template.yml
fix build error due to numpy version
> fix numpy version in build

- python/interpret_community/version.py
- Update interpret-core to 0.2.5
- Add predicted and predicted probabilities to raw explanations to allow model performance tab and other tabs to show information related to y_pred/y_pred_proba for raw explanations
- Update cuML version for GPUKernelExplainer
- Remove shap DenseData from supported input data
- Use scipy logit() function in mimic explainer to fix divide by zero error
> release interpret-community v0.19.0

- python/interpret_community/explanation/explanation.py
- test/raw_explain/test_raw_explanation.py
resolves customer issue
"fix error when creating a raw explanation from an engineered explanation that does not have a DatasetsMixin"
> fix error when creating a raw explanation from an engineered explanation that does not have a DatasetsMixin

- python/README.md
- python/interpret_community/version.py
- fix aggregation logic for raw global importance values to be consistent with local importance values
> release interpret-community 0.19.2

- python/interpret_community/common/gpu_kmeans.py
cuML library added the support for kmeans sampling, so adding the support for version 21.08 (still supports previous versions)
> Update GPU SHAP for kmeans sampling code from cuML

- python/interpret_community/common/gpu_kmeans.py
Fix typo from https://github.com/interpretml/interpret-community/pull/435
Verified to be running on both 21.06 and 21.08 locally.
> Update to check correct version of RAPIDS

- python/setup.py
> Pin numba to less than 0.54.0

- python/interpret_community/version.py
- emergency hotfix to pin numba to less than 0.54.0 to fix shap failures
- update to check correct version of RAPIDS
- update GPU SHAP for kmeans sampling code from cuML
- fix explanation dashboard failing to run on dataset with boolean target labels
> release interpret-community 0.19.3

- devops/templates/test-run-step-template.yml
- requirements-test.txt
> Add flake8-breakpoint to avoid code checkin with active breakpoints

- docs/release-process.md
Some minor updates to the release process docs
> update the release process docs for interpret-community

- test/explanation_utils.py
- test/test_explanation_adapter.py
add unit tests for ExplanationAdapter to increase code coverage
> add tests for ExplanationAdapter for code coverage

- python/setup.py
update interpret-community to the latest version of the ml-wrappers package, v0.0.5
> update interpret-community to ml-wrappers 0.0.5

- python/interpret_community/version.py
- update interpret-community to use new ml-wrappers repository (https://github.com/microsoft/ml-wrappers)
- add tests for ExplanationAdapter for code coverage
- rename test directory from test/ to tests/
- suppress tensorflow warnings that may sometimes occur on import
- add support for serializing explanations using save_explanation and load_explanation with sparse data
- update interpret-community to ml-wrappers 0.0.5
- fix flake8 error on builds
> release interpret-community v0.24.0

- python/interpret_community/version.py
- move PR gate to github actions
- correctly annotate python warnings
- remove devops unit tests from PR gate
- add backcompat test for saving and loading explanations and fix backcompat issue
> release interpret-community v0.24.2

- .github/workflows/python-linting.yml
- devops/templates/test-run-step-template.yml
- python/interpret_community/mimic/mimic_explainer.py
> Add linting workflow for python files

- requirements-dev.txt
fix build failure due to old sqlalchemy dependency
> fix build failure due to old sqlalchemy dependency

- python/interpret_community/common/blackbox_explainer.py
- tests/common_utils.py
- tests/test_explain_model.py
Fix shape check to support other types of wrapped datasets such as BatchDataset.
Also, adds a test to validate explainers work with a BatchDataset now.
Resolves user issue:
https://github.com/interpretml/interpret-community/issues/503
Depends on ml-wrappers PR (and then a release, which was just recently done):
https://github.com/microsoft/ml-wrappers/pull/39
> fix shape check to support other types of wrapped datasets such as BatchDataset

- python/interpret_community/version.py
Release notes:
- [Make function _get_surrogate_model_replication_measure() public](https://github.com/interpretml/interpret-community/commit/3f1e586ebf8a6f1a4f647942ddee276ca4bb93aa)
- [Add linting workflow for python files](https://github.com/interpretml/interpret-community/commit/c7af3d5fbc30b9182e65f1dd6d4812ae79372a15)
- [decrease tolerance on serialization check for macos test builds](https://github.com/interpretml/interpret-community/commit/9d91f8e05f2200ac4bd5e1bd53cb6cf5635924eb)
- [Add python 3.7 tests](https://github.com/interpretml/interpret-community/commit/a463799c98bfbdfa93890cd8fe502ba6f40915b4)
- [replace numpy.array with numpy.ndarray in docs](https://github.com/interpretml/interpret-community/commit/9ba3a83b47fdde6a3921cbcb775d01c939cbe473)
- [Update …
> release interpret-community v0.25.0

- .github/workflows/CI-python.yml
- .github/workflows/Code-Scan.yml
- .github/workflows/python-linting.yml
> Update github action for checkout, upload-artifact and setup-python from version 2 to 3

- python/setup.py
update interpret-community to ml-wrappers 0.2.0
> update interpret-community to ml-wrappers 0.2.0

- python/interpret_community/explanation/explanation.py
- python/interpret_community/mimic/models/linear_model.py
- tests/test_explain_model.py
- tests/test_explanation_dashboard.py
Adding tests for the data() and visualize() methods on our explanations in order to increase code coverage.
> add tests for visualize and data methods on explanation

- python/setup.py
Update interpret-community to the new release of ml-wrappers 0.2.1.
> update interpret-community to ml-wrappers 0.2.1

- python/setup.py
update interpret-community package to the newly released ml-wrappers v0.2.2 package
> update interpret-community to ml-wrappers 0.2.2

- python/interpret_community/version.py
* add tests for visualize and data methods on explanation by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/530
* upgrade interpret-community to new shap 0.41.0 release by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/532
* fix nightly pytorch error on macos by installing numpy from conda by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/535
* fix gated build failures due to incompatibility with new flake8 and old flake8-bugbear and old flake8-logging-format by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/538
* update interpret-community to ml-wrappers 0.2.1 by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/536
* fix explanation adapter error when …
> release interpret-community v0.27.0

- python/setup.py
update interpret-community to ml-wrappers 0.3.0
> update interpret-community to ml-wrappers 0.3.0

- python/setup.py
Signed-off-by: Gaurav Gupta <47334368+gaugup@users.noreply.github.com>
> Update setup.py to update ml-wrappers to 0.4.0

- python/setup.py
update interpret-community to ml-wrappers 0.4.2
> update interpret-community to ml-wrappers 0.4.2

- python/interpret_community/version.py
* Add scheduled builds by @gaugup in https://github.com/interpretml/interpret-community/pull/542
* update interpret-community to ml-wrappers 0.3.0 by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/543
* Update setup.py to update ml-wrappers to 0.4.0 by @gaugup in https://github.com/interpretml/interpret-community/pull/546
* Update python-linting.yml to update setup-python to version 4 by @gaugup in https://github.com/interpretml/interpret-community/pull/547
* update interpret-community to ml-wrappers 0.4.2 by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/548
**Full Changelog**: https://github.com/interpretml/interpret-community/compare/v0.27.0...v0.28.0
> release interpret-community v0.28.0

- python/setup.py
update interpret-community to ml-wrappers 0.4.3
> update interpret-community to ml-wrappers 0.4.3

- python/setup.py
update interpret-community to interpret-core v0.3.2
> update interpret-community to interpret-core v0.3.2

- .github/workflows/CI-python.yml
fix flaky codecov errors in interpret-community by adding retry logic for uploads
> fix flaky codecov errors in interpret-community by adding retry logic for uploads

- python/interpret_community/version.py
* Update python-linting.yml to use python 3.11 by @gaugup in https://github.com/interpretml/interpret-community/pull/563
* Update codecov-action@v2 to codecov-action@v3  by @gaugup in https://github.com/interpretml/interpret-community/pull/564
* fix sklearn build error due to old dependency version installed with newer scipy by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/568
* clean up load method API doc for mimic explainer to reduce confusion by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/567
* fix gated builds due to getargspec deprecation by @imatiach-msft in https://github.com/interpretml/interpret-community/pull/570
* fix auto-generated API sphinx docs build for interpret-community by @imatiach-msft in …
> release interpret-community v0.30.0

- python/setup.py
update interpret-community to shap 0.42.1 and ml-wrappers 0.5.1
> update interpret-community to shap 0.42.1 and ml-wrappers 0.5.1

- python/setup.py
- tests/test_pfi_explainer.py
update interpret to 0.4.4, ml-wrappers to 0.5.2 and enable fixed pfi test
> update interpret to 0.4.4, ml-wrappers to 0.5.2 and enable fixed pfi test

- .github/workflows/CI-python.yml
- devops/templates/test-run-step-template.yml
- python/interpret_community/common/constants.py
- python/interpret_community/shap/deep_explainer.py
- python/interpret_community/tabular_explainer.py
- python/setup.py
update interpret-community to shap 0.43.0
fixes issue:
https://github.com/interpretml/interpret-community/issues/585
> update interpret-community to shap 0.43.0
